version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
      target: gateway
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - API_KEYS=devkey:testkey,prodkey:secret123
      - RATE_LIMIT_WINDOW=60000
      - RATE_LIMIT_MAX_REQUESTS=100
      - AUDIT_LOG_PATH=/app/logs/audit.jsonl
      - TRANSCRIPT_STORAGE_PATH=/app/data/transcripts
      - ECHO_PEER_URL=http://echo-peer:9999
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    depends_on:
      - echo-peer
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  echo-peer:
    build:
      context: .
      dockerfile: Dockerfile
      target: echo-peer
    ports:
      - "9999:9999"
    environment:
      - NODE_ENV=production
      - PORT=9999
      - GATEWAY_URL=http://gateway:8080
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9999/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Redis for session storage (stretch goal)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - redis

volumes:
  redis_data:
